# Generated by Django 5.2.11 on 2026-04-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Campi'},
        ),
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['nome']},
        ),
    ]
