# Generated by Django 5.2.12 on 2026-09-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_categorias_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['numero'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
    ]
