# Generated by Django 5.2.12 on 2026-09-26 13:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pessoa_lancamento_pessoa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='acrescimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O acréscimo não pode ser negativo.')], verbose_name='Acréscimo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(verbose_name='Data da primeira parcela'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O desconto não pode ser negativo.')], verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='intervalo_parcelas',
            field=models.PositiveIntegerField(blank=True, help_text='Obrigatório quando houver mais de uma parcela. Em dias corridos.', null=True, validators=[django.core.validators.MinValueValidator(1, 'O intervalo precisa ser de pelo menos 1 dia.')], verbose_name='Intervalo entre parcelas (dias)'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='parcelas',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de 1. À vista, débito e crédito em uma vez usam 1 parcela.', null=True, validators=[django.core.validators.MinValueValidator(1, 'Informe pelo menos 1 parcela. Compras à vista usam 1.'), django.core.validators.MaxValueValidator(480, 'Use no máximo 480 parcelas.')], verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.pessoa', verbose_name='Cliente/Fornecedor'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Informe um valor maior que zero.')], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='acrescimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O acréscimo não pode ser negativo.')], verbose_name='Acréscimo'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='data',
            field=models.DateField(verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O desconto não pode ser negativo.')], verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.lancamento', verbose_name='Lançamento'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número da parcela'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'Informe um valor maior que zero.')], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'O valor pago precisa ser maior que zero.')], verbose_name='Valor pago'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Formas de pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='forma_pagamento',
            field=models.ForeignKey(help_text='As parcelas nascem com esta forma. Depois, cada parcela pode ser paga de outro jeito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.formapagamento', verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='forma_pagamento',
            field=models.ForeignKey(help_text='Na criação fica igual à do lançamento. Altere aqui se esta parcela for paga de outra forma.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.formapagamento', verbose_name='Forma de pagamento'),
        ),
        migrations.AddConstraint(
            model_name='parcela',
            constraint=models.UniqueConstraint(fields=('lancamento', 'numero'), name='parcela_unica_por_lancamento'),
        ),
    ]
