# Generated by Django 5.2.12 on 2026-09-29 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_ajustes_financeiros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de lançamento',
                'verbose_name_plural': 'Centros de lançamento',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='status',
        ),
        migrations.AddField(
            model_name='lancamento',
            name='agrupado',
            field=models.BooleanField(default=False, help_text='Marque se este lançamento junta várias notas em um só.', verbose_name='Lançamento agrupado'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='declara_ir',
            field=models.BooleanField(default=False, help_text='Marque se este lançamento deve entrar na declaração do imposto de renda.', verbose_name='Declara no imposto de renda'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='numero',
            field=models.CharField(blank=True, help_text='Número da nota, do boleto ou do documento. Opcional.', max_length=30, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='documento',
            field=models.CharField(max_length=18, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='pessoa',
            constraint=models.UniqueConstraint(fields=('criado_por', 'documento'), name='pessoa_documento_unico_por_usuario'),
        ),
        migrations.AddField(
            model_name='centro',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='centro',
            field=models.ForeignKey(blank=True, help_text='Opcional. Use para acompanhar uma viagem, reforma ou projeto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.centro', verbose_name='Centro de lançamento'),
        ),
    ]
